# Generated by Django 5.2.4 on 2025-07-11 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='custom_user_email_55dec9_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='custom_user_is_prem_905f1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='custom_user_created_3135d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='memberprofile',
            name='member_prof_company_3c5d44_idx',
        ),
        migrations.RemoveIndex(
            model_name='memberprofile',
            name='member_prof_created_ca0b25_idx',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='notification_preferences',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
        migrations.AlterModelTable(
            name='memberprofile',
            table=None,
        ),
    ]
