# Generated by Django 5.2.4 on 2025-07-11 13:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('meeting_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person'), ('hybrid', 'Hybrid')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('online_link', models.URLField(blank=True)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_members_only', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='groups.group')),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], db_index=True, default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('payment_required', models.BooleanField(default=False)),
                ('payment_completed', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_attendances',
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['title'], name='meetings_title_b87c68_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type'], name='meetings_meeting_af3320_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status'], name='meetings_status_85fffd_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_datetime'], name='meetings_start_d_20565d_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['is_members_only'], name='meetings_is_memb_5dbe19_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['created_at'], name='meetings_created_dc468a_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['status'], name='meeting_att_status_6d0789_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['payment_completed'], name='meeting_att_payment_57f69a_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['registered_at'], name='meeting_att_registe_b7ecd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendance',
            unique_together={('meeting', 'user')},
        ),
    ]
