# Generated by Django 5.2.4 on 2025-07-11 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_groups_name_2de3f0_idx_and_more'),
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meeting',
            name='meetings_title_b87c68_idx',
        ),
        migrations.RemoveIndex(
            model_name='meeting',
            name='meetings_meeting_af3320_idx',
        ),
        migrations.RemoveIndex(
            model_name='meeting',
            name='meetings_status_85fffd_idx',
        ),
        migrations.RemoveIndex(
            model_name='meeting',
            name='meetings_start_d_20565d_idx',
        ),
        migrations.RemoveIndex(
            model_name='meeting',
            name='meetings_is_memb_5dbe19_idx',
        ),
        migrations.RemoveIndex(
            model_name='meeting',
            name='meetings_created_dc468a_idx',
        ),
        migrations.RemoveIndex(
            model_name='meetingattendance',
            name='meeting_att_status_6d0789_idx',
        ),
        migrations.RemoveIndex(
            model_name='meetingattendance',
            name='meeting_att_payment_57f69a_idx',
        ),
        migrations.RemoveIndex(
            model_name='meetingattendance',
            name='meeting_att_registe_b7ecd7_idx',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_members_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person'), ('hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='meeting',
            table=None,
        ),
        migrations.AlterModelTable(
            name='meetingattendance',
            table=None,
        ),
    ]
