# Generated by Django 5.2.4 on 2025-07-11 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='group',
            name='groups_name_2de3f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='group',
            name='groups_is_priv_e7005c_idx',
        ),
        migrations.RemoveIndex(
            model_name='group',
            name='groups_created_d34ebd_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupmembership',
            name='group_membe_role_ae792e_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupmembership',
            name='group_membe_is_acti_79ec35_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupmembership',
            name='group_membe_joined__4d16e3_idx',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='group',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, upload_to='groups/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='group',
            table=None,
        ),
        migrations.AlterModelTable(
            name='groupmembership',
            table=None,
        ),
    ]
